services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: Paynexus_redis_container
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: test        # Sets the password for Redis
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

